=== vishnu2347265/WEB_STACK/Lab_4 Xml/EeCommerce-xml-main/lab4(XML)/myEcom.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="products">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" type="productType" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="product_id" type="xs:string" />
            <xs:element name="product_name" type="xs:string" />
            <xs:element name="price" type="priceType" />
            <xs:element name="available_quantity" type="xs:string" />
            <xs:element name="category" type="categoryType" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="5" />
            <xs:maxInclusive value="500" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="categoryType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Electronics" />
            <xs:enumeration value="Clothing" />
            <xs:enumeration value="Books" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== vishnu2347265/WEB_STACK/Lab_4 Xml/EeCommerce-xml-main/lab4(XML)/myEcom.xml
<?xml version="1.0" encoding="UTF-8"?>


<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="myEcom.xsd">
    <product>
        <product_id>101</product_id>
        <product_name>macbook air</product_name>
        <price>350</price>
        <available_quantity>
        20</available_quantity>
        <category>Electronics</category>
    </product>
    <product>
        <product_id>501</product_id>
        <product_name>Gucci zip jacket</product_name>
        <price>280</price>
        <available_quantity>
        8</available_quantity>
        <category>Clothing</category>
    </product>
    <product>
        <product_id>201</product_id>
        <product_name>rich dad poor dad</product_name>
        <price>12</price>
        <available_quantity>
        147</available_quantity>
        <category>Books</category>
    </product>
</products>
